-- Passenger table schema (Titanic dataset + Wikipedia-sourced columns).
-- Original DDL generated by the ERD tool in pgAdmin 4.

BEGIN;

CREATE TABLE IF NOT EXISTS public.passenger
(
    passengerid integer NOT NULL,
    survived double precision,
    pclass integer,
    name text COLLATE pg_catalog."default",
    sex text COLLATE pg_catalog."default",
    age double precision,
    sibsp integer,
    parch integer,
    ticket text COLLATE pg_catalog."default",
    fare double precision,
    cabin text COLLATE pg_catalog."default",
    embarked text COLLATE pg_catalog."default",
    wikiid double precision,
    name_wiki text COLLATE pg_catalog."default",
    age_wiki double precision,
    hometown text COLLATE pg_catalog."default",
    boarded text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    lifeboat text COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    class integer,
    CONSTRAINT passenger_pkey PRIMARY KEY (passengerid)
);

-- Indexes for the columns most commonly filtered or grouped on.
CREATE INDEX IF NOT EXISTS passenger_pclass_idx   ON public.passenger (pclass);
CREATE INDEX IF NOT EXISTS passenger_sex_idx      ON public.passenger (sex);
CREATE INDEX IF NOT EXISTS passenger_embarked_idx ON public.passenger (embarked);
CREATE INDEX IF NOT EXISTS passenger_survived_idx ON public.passenger (survived);
CREATE INDEX IF NOT EXISTS passenger_ticket_idx   ON public.passenger (ticket);

END;
